### ISSUE TITLE
是服务器问题吗？打开网站或者跳转页面一直会在loading页面卡一会 

### ISSUE THREAD

**Issue by Yakumo-Yukari** [Ocyss/QiuBlog#1]
是服务器问题吗？打开网站或者跳转页面一直会在loading页面卡一会 ，然后进入文章内容页面也会显示 加载中 会加载一会  响应速度有点慢

**Comment by Ocyss** [comment]
服务器是香港的,但应该有CN2加速,除个别地方有点慢,我这ping的延迟是38左右

使用的是SSR渲染,如果在loading卡的久那有可能是网络不好
